---
- name: Hansung RAG Agent 인프라 환경 구축 자동화
  hosts: all
  become: yes
  vars_files:
    - group_vars/secrets.yml
  
  roles:

    - role: ram_optimization # RAM 최적화 구성
      tags:
        - ram

    - role: aws_config # aws agent 구성
      tags:
        - aws

    - role: docker_setup # docker engine & compose plugin 설치
      tags:
        - docker

    - role: nginx
      tags:
        - nginx

    - role: cloudwatch # cloudwatch_agent 통한 자동 모니터링 환경 구축
      tags:
        - cloudwatch

    - role: grafana
      tags:
        - grafana
